In [42]:
import pandas as pd

In [43]:
df_main = pd.read_csv('../Datasets/df_main.csv', index_col=0).reset_index(drop=True)

In [44]:
df_main

,fips,Staffed_Beds,Total_Discharges,Patient_Days,Gross_Patient_Revenue,Hospitals,Local_Hospital,ADI_NATRANK,ADI_STATERNK,2021/3/10_x,...,pct_veterans_male,pop_adult_education_bachelors_or_higher,pop_adult_education_high_school,pop_adult_education_less_than_high_school,pop_adult_education_some_college_or_associates,pop_lived_in_same_house_last_year,pop_total,pop_veterans,pop_veterans_female,pop_veterans_male
0,1001,77.0,3049.0,15984.0,250284.0,1.0,yes,66.977778,4.355556,6400.0,...,88.111428,8464,8819,2886,9201,48039.0,55639,4559,542,4017
1,1003,301.0,18080.0,78361.0,2481966.0,3.0,yes,51.534483,2.655172,20012.0,...,91.796182,36513,29636,10250,34448,191350.0,218289,19174,1573,17601
2,1005,47.0,1055.0,4571.0,76099.0,1.0,yes,90.900000,7.950000,2161.0,...,92.014925,1409,4525,3131,3955,20996.0,25026,1340,107,1233
3,1007,156.0,229.0,1053.0,31288.0,1.0,yes,83.411765,6.647059,2469.0,...,94.771783,1388,5442,2189,3292,19347.0,22374,1205,63,1142
4,1009,0.0,0.0,0.0,0.0,0.0,no,72.325581,4.906977,6260.0,...,93.603286,4158,9757,4494,11023,52428.0,57755,3408,218,3190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,56037,58.0,1279.0,4742.0,207720.0,2.0,yes,54.088235,6.147059,3861.0,...,92.318291,5084,7298,1656,8906,34743.0,43352,2903,223,2680
3120,56039,121.0,1711.0,5932.0,273723.0,1.0,yes,6.473684,1.000000,3404.0,...,88.149938,7762,2278,871,3390,18448.0,23356,827,98,729
3121,56041,32.0,803.0,1627.0,105109.0,1.0,yes,57.058824,7.117647,2084.0,...,92.226890,1974,3960,664,3627,17520.0,20374,952,74,878
3122,56043,0.0,0.0,0.0,0.0,0.0,no,59.555556,7.777778,888.0,...,96.088434,1013,1021,308,1457,6667.0,7933,588,23,565
3123,56045,0.0,0.0,0.0,0.0,0.0,no,63.600000,8.600000,623.0,...,92.831540,668,1312,199,1346,5472.0,6942,558,40,518

In [45]:
print(list(df_main.columns))

['fips', 'Staffed_Beds', 'Total_Discharges', 'Patient_Days', 'Gross_Patient_Revenue', 'Hospitals', 'Local_Hospital', 'ADI_NATRANK', 'ADI_STATERNK', '2021/3/10_x', '2022/3/10_x', '2023/3/10_x', '2021/3/10_y', '2022/3/10_y', '2023/3/10_y', 'Value_education', 'Value_poverty', 'Value_unemployment', 'pct_pop_commute_departure_0000_to_0459', 'pct_pop_commute_departure_0500_to_0529', 'pct_pop_commute_departure_0530_to_0559', 'pct_pop_commute_departure_0600_to_0629', 'pct_pop_commute_departure_0630_to_0659', 'pct_pop_commute_departure_0700_to_0729', 'pct_pop_commute_departure_0730_to_0759', 'pct_pop_commute_departure_0800_to_0829', 'pct_pop_commute_departure_0830_to_0859', 'pct_pop_commute_departure_0900_to_0959', 'pct_pop_commute_departure_1000_to_1059', 'pct_pop_commute_departure_1100_to_1159', 'pct_pop_commute_departure_1200_to_1559', 'pct_pop_commute_departure_1600_to_2359', 'pct_pop_commute_travel_time_10_to_14_min', 'pct_pop_commute_travel_time_15_to_19_min', 'pct_pop_commute_travel_time_20_to_24_min', 'pct_pop_commute_travel_time_25_to_29_min', 'pct_pop_commute_travel_time_30_to_34_min', 'pct_pop_commute_travel_time_35_to_39_min', 'pct_pop_commute_travel_time_40_to_44_min', 'pct_pop_commute_travel_time_45_to_59_min', 'pct_pop_commute_travel_time_5_to_9_min', 'pct_pop_commute_travel_time_60_to_89_min', 'pct_pop_commute_travel_time_90_min_or_more', 'pct_pop_commute_travel_time_under_5_min', 'pct_pop_commutes_by_bicycle', 'pct_pop_commutes_by_car_truck_van_alone', 'pct_pop_commutes_by_car_truck_van_any', 'pct_pop_commutes_by_car_truck_van_carpool', 'pct_pop_commutes_by_public_transport_any', 'pct_pop_commutes_by_public_transport_bus', 'pct_pop_commutes_by_public_transport_ferry', 'pct_pop_commutes_by_public_transport_lightrail', 'pct_pop_commutes_by_public_transport_rail', 'pct_pop_commutes_by_public_transport_subway', 'pct_pop_commutes_by_taxi_motorcycle_or_other', 'pct_pop_commutes_by_walking', 'pct_pop_has_0_vehicles_available', 'pct_pop_has_1_vehicles_available', 'pct_pop_has_2_vehicles_available', 'pct_pop_has_3_or_more_vehicles_available', 'pct_pop_works_from_home', 'pct_pop_works_in_county_of_residence', 'pct_pop_works_in_state_different_county_of_residence', 'pct_pop_works_in_state_of_residence', 'pct_pop_works_outside_state_of_residence', 'pop_commute_departure_0000_to_0459', 'pop_commute_departure_0500_to_0529', 'pop_commute_departure_0530_to_0559', 'pop_commute_departure_0600_to_0629', 'pop_commute_departure_0630_to_0659', 'pop_commute_departure_0700_to_0729', 'pop_commute_departure_0730_to_0759', 'pop_commute_departure_0800_to_0829', 'pop_commute_departure_0830_to_0859', 'pop_commute_departure_0900_to_0959', 'pop_commute_departure_1000_to_1059', 'pop_commute_departure_1100_to_1159', 'pop_commute_departure_1200_to_1559', 'pop_commute_departure_1600_to_2359', 'pop_commute_travel_time_10_to_14_min', 'pop_commute_travel_time_15_to_19_min', 'pop_commute_travel_time_20_to_24_min', 'pop_commute_travel_time_25_to_29_min', 'pop_commute_travel_time_30_to_34_min', 'pop_commute_travel_time_35_to_39_min', 'pop_commute_travel_time_40_to_44_min', 'pop_commute_travel_time_45_to_59_min', 'pop_commute_travel_time_5_to_9_min', 'pop_commute_travel_time_60_to_89_min', 'pop_commute_travel_time_90_min_or_more', 'pop_commute_travel_time_under_5_min', 'pop_commutes_by_bicycle', 'pop_commutes_by_car_truck_van_alone', 'pop_commutes_by_car_truck_van_any', 'pop_commutes_by_car_truck_van_carpool', 'pop_commutes_by_public_transport_any', 'pop_commutes_by_public_transport_bus', 'pop_commutes_by_public_transport_ferry', 'pop_commutes_by_public_transport_lightrail', 'pop_commutes_by_public_transport_rail', 'pop_commutes_by_public_transport_subway', 'pop_commutes_by_taxi_motorcycle_or_other', 'pop_commutes_by_walking', 'pop_has_0_vehicles_available', 'pop_has_1_vehicles_available', 'pop_has_2_vehicles_available', 'pop_has_3_or_more_vehicles_available', 'pop_works_from_home', 'pop_works_in_county_of_residence', 'pop_works_in_state_different_county_of_residence', 'pop_works_in_state_of_residence', 'pop_works_outside_state_of_residence', 'geometry_x', 'median_age', 'median_age_female', 'median_age_male', 'pct_pop_birthplace_foreign', 'pct_pop_birthplace_us', 'pct_pop_citizenship_non_us', 'pct_pop_citizenship_us_native', 'pct_pop_citizenship_us_naturalized', 'pct_pop_ethnicity_hispanic_latino', 'pct_pop_ethnicity_non_hispanic', 'pct_pop_race_asian', 'pct_pop_race_black', 'pct_pop_race_hawaiian_pacific_islander', 'pct_pop_race_multiple', 'pct_pop_race_native_american', 'pct_pop_race_other', 'pct_pop_race_white', 'pct_pop_sex_female', 'pct_pop_sex_female_age_10_to_14', 'pct_pop_sex_female_age_15_to_17', 'pct_pop_sex_female_age_18_to_19', 'pct_pop_sex_female_age_20', 'pct_pop_sex_female_age_21', 'pct_pop_sex_female_age_22_to_24', 'pct_pop_sex_female_age_25_to_29', 'pct_pop_sex_female_age_30_to_34', 'pct_pop_sex_female_age_35_to_39', 'pct_pop_sex_female_age_40_to_44', 'pct_pop_sex_female_age_45_to_49', 'pct_pop_sex_female_age_50_to_54', 'pct_pop_sex_female_age_55_to_59', 'pct_pop_sex_female_age_5_to_9', 'pct_pop_sex_female_age_60_to_61', 'pct_pop_sex_female_age_62_to_64', 'pct_pop_sex_female_age_65_to_66', 'pct_pop_sex_female_age_67_to_69', 'pct_pop_sex_female_age_70_to_74', 'pct_pop_sex_female_age_75_to_79', 'pct_pop_sex_female_age_80_to_84', 'pct_pop_sex_female_age_85_and_over', 'pct_pop_sex_female_age_under_5', 'pct_pop_sex_male', 'pct_pop_sex_male_age_10_to_14', 'pct_pop_sex_male_age_15_to_17', 'pct_pop_sex_male_age_18_to_19', 'pct_pop_sex_male_age_20', 'pct_pop_sex_male_age_21', 'pct_pop_sex_male_age_22_to_24', 'pct_pop_sex_male_age_25_to_29', 'pct_pop_sex_male_age_30_to_34', 'pct_pop_sex_male_age_35_to_39', 'pct_pop_sex_male_age_40_to_44', 'pct_pop_sex_male_age_45_to_49', 'pct_pop_sex_male_age_50_to_54', 'pct_pop_sex_male_age_55_to_59', 'pct_pop_sex_male_age_5_to_9', 'pct_pop_sex_male_age_60_to_61', 'pct_pop_sex_male_age_62_to_64', 'pct_pop_sex_male_age_65_to_66', 'pct_pop_sex_male_age_67_to_69', 'pct_pop_sex_male_age_70_to_74', 'pct_pop_sex_male_age_75_to_79', 'pct_pop_sex_male_age_80_to_84', 'pct_pop_sex_male_age_85_and_over', 'pct_pop_sex_male_age_under_5', 'pop_birthplace_foreign', 'pop_birthplace_us', 'pop_citizenship_non_us', 'pop_citizenship_us_native', 'pop_citizenship_us_naturalized', 'pop_ethnicity_hispanic_latino', 'pop_ethnicity_non_hispanic', 'pop_race_asian', 'pop_race_black', 'pop_race_hawaiian_pacific_islander', 'pop_race_multiple', 'pop_race_native_american', 'pop_race_other', 'pop_race_white', 'pop_sex_female', 'pop_sex_female_age_10_to_14', 'pop_sex_female_age_15_to_17', 'pop_sex_female_age_18_to_19', 'pop_sex_female_age_20', 'pop_sex_female_age_21', 'pop_sex_female_age_22_to_24', 'pop_sex_female_age_25_to_29', 'pop_sex_female_age_30_to_34', 'pop_sex_female_age_35_to_39', 'pop_sex_female_age_40_to_44', 'pop_sex_female_age_45_to_49', 'pop_sex_female_age_50_to_54', 'pop_sex_female_age_55_to_59', 'pop_sex_female_age_5_to_9', 'pop_sex_female_age_60_to_61', 'pop_sex_female_age_62_to_64', 'pop_sex_female_age_65_to_66', 'pop_sex_female_age_67_to_69', 'pop_sex_female_age_70_to_74', 'pop_sex_female_age_75_to_79', 'pop_sex_female_age_80_to_84', 'pop_sex_female_age_85_and_over', 'pop_sex_female_age_under_5', 'pop_sex_male', 'pop_sex_male_age_10_to_14', 'pop_sex_male_age_15_to_17', 'pop_sex_male_age_18_to_19', 'pop_sex_male_age_20', 'pop_sex_male_age_21', 'pop_sex_male_age_22_to_24', 'pop_sex_male_age_25_to_29', 'pop_sex_male_age_30_to_34', 'pop_sex_male_age_35_to_39', 'pop_sex_male_age_40_to_44', 'pop_sex_male_age_45_to_49', 'pop_sex_male_age_50_to_54', 'pop_sex_male_age_55_to_59', 'pop_sex_male_age_5_to_9', 'pop_sex_male_age_60_to_61', 'pop_sex_male_age_62_to_64', 'pop_sex_male_age_65_to_66', 'pop_sex_male_age_67_to_69', 'pop_sex_male_age_70_to_74', 'pop_sex_male_age_75_to_79', 'pop_sex_male_age_80_to_84', 'pop_sex_male_age_85_and_over', 'pop_sex_male_age_under_5', 'pop_total_x', 'geometry_y', 'households_total_x', 'households_with_annual_income_100000_to_124999', 'households_with_annual_income_125000_to_149999', 'households_with_annual_income_150000_to_199999', 'households_with_annual_income_200000_or_more', 'households_with_annual_income_30000_to_39999', 'households_with_annual_income_40000_to_49999', 'households_with_annual_income_50000_to_59999', 'households_with_annual_income_60000_to_75499', 'households_with_annual_income_75000_to_99999', 'households_with_annual_income_less_than_30000', 'pct_households_with_annual_income_100000_to_124999', 'pct_households_with_annual_income_125000_to_149999', 'pct_households_with_annual_income_150000_to_199999', 'pct_households_with_annual_income_200000_or_more', 'pct_households_with_annual_income_30000_to_39999', 'pct_households_with_annual_income_40000_to_49999', 'pct_households_with_annual_income_50000_to_59999', 'pct_households_with_annual_income_60000_to_75499', 'pct_households_with_annual_income_75000_to_99999', 'pct_households_with_annual_income_less_than_30000', 'pct_in_labor_force_status_armed_forces', 'pct_in_labor_force_status_civilian_employed', 'pct_in_labor_force_status_civilian_unemployed', 'pct_pop_at_100_to_149_pct_poverty_level', 'pct_pop_at_or_above_150_pct_poverty_level', 'pct_pop_below_100_pct_poverty_level', 'pct_pop_employment_status_in_labor_force', 'pct_pop_employment_status_not_in_labor_force', 'pct_pop_received_ssi_foodstamps_snap_past_year', 'pct_pop_works_industry_agriculture_forestry_fishing_hunting_mining', 'pct_pop_works_industry_armed_forces', 'pct_pop_works_industry_arts_entertainment_food_services', 'pct_pop_works_industry_construction', 'pct_pop_works_industry_educational_healthcare_social_assistance', 'pct_pop_works_industry_finance_insurance_real_estate', 'pct_pop_works_industry_information', 'pct_pop_works_industry_manufacturing', 'pct_pop_works_industry_other_services', 'pct_pop_works_industry_professional_scientific_management', 'pct_pop_works_industry_public_administration', 'pct_pop_works_industry_retail_trade', 'pct_pop_works_industry_transportation_warehousing_utilities', 'pct_pop_works_industry_wholesale_trade', 'pct_pop_works_occupation_construction_maintenance', 'pct_pop_works_occupation_management_business_science_arts', 'pct_pop_works_occupation_military_related', 'pct_pop_works_occupation_production_transportation_moving', 'pct_pop_works_occupation_sales_office', 'pct_pop_works_occupation_service', 'pop_at_100_to_149_pct_poverty_level', 'pop_at_or_above_150_pct_poverty_level', 'pop_below_100_pct_poverty_level', 'pop_employment_status_in_labor_force', 'pop_employment_status_in_labor_force_armed_forces', 'pop_employment_status_in_labor_force_civilian_employed', 'pop_employment_status_in_labor_force_civilian_unemployed', 'pop_employment_status_not_in_labor_force', 'pop_received_ssi_foodstamps_snap_past_year', 'pop_total_y', 'pop_works_industry_agriculture_forestry_fishing_hunting_mining', 'pop_works_industry_armed_forces', 'pop_works_industry_arts_entertainment_food_services', 'pop_works_industry_construction', 'pop_works_industry_educational_healthcare_social_assistance', 'pop_works_industry_finance_insurance_real_estate', 'pop_works_industry_information', 'pop_works_industry_manufacturing', 'pop_works_industry_other_services', 'pop_works_industry_professional_scientific_management', 'pop_works_industry_public_administration', 'pop_works_industry_retail_trade', 'pop_works_industry_transportation_warehousing_utilities', 'pop_works_industry_wholesale_trade', 'pop_works_occupation_construction_maintenance', 'pop_works_occupation_management_business_science_arts', 'pop_works_occupation_military_related', 'pop_works_occupation_production_transportation_moving', 'pop_works_occupation_sales_office', 'pop_works_occupation_service', 'geometry', 'households_cohabiting_couple', 'households_cohabiting_couple_with_children', 'households_female_head', 'households_female_head_with_children', 'households_male_head', 'households_male_head_with_children', 'households_married_couple', 'households_married_couple_with_children', 'households_total_y', 'households_with_computing_devices_desktop_laptop', 'households_with_computing_devices_none', 'households_with_computing_devices_other_computer', 'households_with_computing_devices_smartphone', 'households_with_computing_devices_tablet', 'households_with_computing_devices_total', 'households_with_no_internet_access', 'pct_households_cohabiting_couple', 'pct_households_cohabiting_couple_with_children', 'pct_households_female_head', 'pct_households_female_head_with_children', 'pct_households_male_head', 'pct_households_male_head_with_children', 'pct_households_married_couple', 'pct_households_married_couple_with_children', 'pct_households_with_computing_devices_desktop_laptop', 'pct_households_with_computing_devices_none', 'pct_households_with_computing_devices_other_computer', 'pct_households_with_computing_devices_smartphone', 'pct_households_with_computing_devices_tablet', 'pct_households_with_computing_devices_total', 'pct_households_with_no_internet_access', 'pct_pop_adult_education_bachelors_or_higher', 'pct_pop_adult_education_high_school', 'pct_pop_adult_education_less_than_high_school', 'pct_pop_adult_education_some_college_or_associates', 'pct_pop_lived_in_same_house_last_year', 'pct_pop_veterans', 'pct_veterans_female', 'pct_veterans_male', 'pop_adult_education_bachelors_or_higher', 'pop_adult_education_high_school', 'pop_adult_education_less_than_high_school', 'pop_adult_education_some_college_or_associates', 'pop_lived_in_same_house_last_year', 'pop_total', 'pop_veterans', 'pop_veterans_female', 'pop_veterans_male']

### Dropping percentages and geometry

In [46]:
cols_to_drop = df_main.filter(like='pct').columns
df_main = df_main.drop(columns=cols_to_drop)

In [47]:
cols_to_drop = df_main.filter(like='geometry').columns
df_main = df_main.drop(columns=cols_to_drop)

In [48]:
df_main

,fips,Staffed_Beds,Total_Discharges,Patient_Days,Gross_Patient_Revenue,Hospitals,Local_Hospital,ADI_NATRANK,ADI_STATERNK,2021/3/10_x,...,households_with_no_internet_access,pop_adult_education_bachelors_or_higher,pop_adult_education_high_school,pop_adult_education_less_than_high_school,pop_adult_education_some_college_or_associates,pop_lived_in_same_house_last_year,pop_total,pop_veterans,pop_veterans_female,pop_veterans_male
0,1001,77.0,3049.0,15984.0,250284.0,1.0,yes,66.977778,4.355556,6400.0,...,3307,8464,8819,2886,9201,48039.0,55639,4559,542,4017
1,1003,301.0,18080.0,78361.0,2481966.0,3.0,yes,51.534483,2.655172,20012.0,...,10018,36513,29636,10250,34448,191350.0,218289,19174,1573,17601
2,1005,47.0,1055.0,4571.0,76099.0,1.0,yes,90.900000,7.950000,2161.0,...,2700,1409,4525,3131,3955,20996.0,25026,1340,107,1233
3,1007,156.0,229.0,1053.0,31288.0,1.0,yes,83.411765,6.647059,2469.0,...,1520,1388,5442,2189,3292,19347.0,22374,1205,63,1142
4,1009,0.0,0.0,0.0,0.0,0.0,no,72.325581,4.906977,6260.0,...,3920,4158,9757,4494,11023,52428.0,57755,3408,218,3190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,56037,58.0,1279.0,4742.0,207720.0,2.0,yes,54.088235,6.147059,3861.0,...,1498,5084,7298,1656,8906,34743.0,43352,2903,223,2680
3120,56039,121.0,1711.0,5932.0,273723.0,1.0,yes,6.473684,1.000000,3404.0,...,540,7762,2278,871,3390,18448.0,23356,827,98,729
3121,56041,32.0,803.0,1627.0,105109.0,1.0,yes,57.058824,7.117647,2084.0,...,531,1974,3960,664,3627,17520.0,20374,952,74,878
3122,56043,0.0,0.0,0.0,0.0,0.0,no,59.555556,7.777778,888.0,...,429,1013,1021,308,1457,6667.0,7933,588,23,565
3123,56045,0.0,0.0,0.0,0.0,0.0,no,63.600000,8.600000,623.0,...,367,668,1312,199,1346,5472.0,6942,558,40,518

### Model Fitting

In [68]:
df_main = df_main.drop(columns=['pop_total_x', 'pop_total_y'])

KeyError: "['pop_total_x', 'pop_total_y'] not found in axis"

In [69]:
non_numeric_columns = df_main.select_dtypes(exclude='number').columns
print("Non-numeric columns:")
for column in non_numeric_columns:
    print(column)

Non-numeric columns:

In [70]:
df_main['Local_Hospital'] = df_main['Local_Hospital'].replace({'yes': 1, 'no': 0})

In [93]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [90]:
X = df_main.drop(columns=['fips','2021/3/10_x', '2022/3/10_x', '2023/3/10_x', '2021/3/10_y', '2022/3/10_y', '2023/3/10_y'])
y = df_main['2021/3/10_y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [87]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [94]:
# Obtain the R^2 score for your test data
score = lin_reg.score(X_test, y_test)
print("R^2 Score:", score)

# If you want to compute the mean squared error
y_pred = lin_reg.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

R^2 Score: 0.98351138472049
Mean Squared Error: 3613.811400048893

In [88]:
print(f"Intercept: {lin_reg.intercept_}")
print(f"Coefficients: {lin_reg.coef_}")

Intercept: -5.698191523735488
Coefficients: [-3.89127082e-02 -8.84110758e-04  3.45746010e-04 -2.80813002e-06
 -1.20963944e+00 -4.42641950e-01  1.51915434e-01  3.83181033e-01
  8.70421015e-02  2.13544908e-01  2.04787024e-01  1.20755804e-02
  2.31320146e-02  9.08322087e-03 -9.97876416e-03  4.31061713e-03
  6.03891175e-03 -9.44046129e-03 -2.89951373e-04 -3.04788853e-03
 -3.91633791e-03  1.16126125e-02 -1.68925999e-02 -4.07494035e-03
 -4.30062605e-03  5.34180767e-03 -6.31528066e-04 -9.40027464e-04
  4.49522573e-03  3.52395419e-03 -1.02302398e-02  7.98849747e-03
 -6.12977032e-03  5.80565733e-03 -1.36533567e-03  3.31986282e-03
  3.13328386e-03  1.11011778e-02 -1.98268252e-03  7.74336135e-04
  2.75701868e-03  4.62372497e-02  6.68158198e-03 -6.52247682e-03
  2.90698568e-03 -6.44775808e-03 -5.51633326e-04 -8.22434399e-03
 -1.58956192e-03 -3.63098746e-04  1.08683936e-02 -2.98419259e-03
 -5.03956135e-03 -6.31575226e-02  8.14026707e-04  2.56857037e-03
  3.38259709e-03  6.70560869e-03 -3.05790308e-01 -3.61709318e-01
  3.22873649e-01  3.52414131e-04  1.90832900e-04 -1.99990657e-03
  1.90832905e-04  2.35232068e-03  9.84026308e-04 -4.40779247e-04
 -1.16347704e-03 -1.11489523e-03  5.96329715e-03 -8.15403087e-03
  4.24732961e-03 -1.11334220e-05  7.76156832e-04  5.78033434e-03
  1.27769337e-02 -6.94385246e-02 -4.77230296e-02  4.46877796e-02
  8.81508813e-03  5.50346822e-03  2.97491804e-03 -5.47680536e-02
 -3.48237697e-02 -3.36884048e-02  4.47383094e-02  1.82894925e-02
  2.78831096e-02 -9.42898495e-03  1.49760660e-02  6.29414940e-02
 -1.54367669e-02 -4.25024473e-02 -5.94428511e-03  3.43039835e-02
 -4.41883265e-03  4.55424111e-02  5.20379605e-04 -5.23708729e-03
  1.50519236e-02  1.29557555e-02  5.63425557e-03 -1.45743929e-02
  4.27322160e-03  7.48002104e-04  3.47373673e-02  1.15031150e-02
 -6.93006877e-03 -2.75940059e-03 -2.60680833e-03  2.19537596e-03
 -4.02159354e-02  2.01758504e-02 -2.56742457e-02 -1.25663769e-02
  3.62939644e-03  6.11628106e-03  1.77261237e-02 -2.84285420e-02
  3.30795474e-02 -3.89750305e-02 -3.32501950e-04 -4.16187817e-03
 -2.40665186e-03  5.12715555e-03  6.05041120e-03 -2.86661269e-03
  5.52439525e-03 -8.61174198e-03  2.37216984e-02 -1.47769046e-02
 -4.20307265e-03 -1.17205548e-02 -3.16001763e-02 -1.10741117e-01
  3.17113951e-02  4.74295458e-02 -2.48089567e-04 -4.77770817e-03
 -2.94784024e-02  1.24642769e-01 -3.04659159e-03 -2.23035375e-02
 -6.90562570e-03 -7.88715878e-03  1.41797734e-02 -7.12338026e-03
 -1.49653591e-02 -1.35393339e-02 -1.13363240e-02  3.18170352e-03
 -7.65221947e-03 -7.67810733e-03 -3.88622164e-03  8.17313146e-03
  6.79479053e-03 -5.35181842e-03  3.95424203e-03  4.04081809e-04
 -2.98456421e-02  6.75377004e-02  2.56496586e-03  2.14996543e-02
  2.02141234e-02 -1.48458941e-02  2.90467461e-03  2.12644592e-02
 -4.16187817e-03 -1.69504568e-03 -1.09559399e-03 -1.44502854e-02
  7.60385382e-03 -8.40623376e-03 -3.06628417e-03  8.52727829e-03
 -1.03583479e-03  3.29397985e-03  6.57959133e-03 -2.63155227e-03
  1.34788765e-03  5.43247007e-04 -3.79981738e-03 -1.51761106e-02
  1.13762932e-02]

In [81]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.feature_selection import SelectKBest, f_classif

In [84]:
kbest_selector = SelectKBest(mutual_info_classif, k=2)
X_new = kbest_selector.fit_transform(X, y)

KeyboardInterrupt:

In [77]:
selected_features = np.where(kbest_selector.get_support())[0]
print("Selected feature indices:", selected_features)

Selected feature indices: [ 35  44  45  47  48  50  62  64  66  67  74  76  77  78  87  88  89  91
  96  97  98  99 101 102 112 113 115 123 129 130 134 138 139 140 147 149
 153 154 158 159 160 162 163 164 171 176 178 179 181 182]

In [ ]:
selected_column_names = X.columns[kbest_selector.get_support()].tolist()
print("Selected column names:", selected_column_names)

Selected column names: ['pop_commute_travel_time_60_to_89_min', 'pop_commutes_by_public_transport_ferry', 'pop_commutes_by_public_transport_lightrail', 'pop_commutes_by_public_transport_subway', 'pop_commutes_by_taxi_motorcycle_or_other', 'pop_has_0_vehicles_available', 'pop_birthplace_foreign', 'pop_citizenship_non_us', 'pop_citizenship_us_naturalized', 'pop_ethnicity_hispanic_latino', 'pop_race_other', 'pop_sex_female', 'pop_sex_female_age_10_to_14', 'pop_sex_female_age_15_to_17', 'pop_sex_female_age_45_to_49', 'pop_sex_female_age_50_to_54', 'pop_sex_female_age_55_to_59', 'pop_sex_female_age_60_to_61', 'pop_sex_female_age_75_to_79', 'pop_sex_female_age_80_to_84', 'pop_sex_female_age_85_and_over', 'pop_sex_female_age_under_5', 'pop_sex_male_age_10_to_14', 'pop_sex_male_age_15_to_17', 'pop_sex_male_age_50_to_54', 'pop_sex_male_age_55_to_59', 'pop_sex_male_age_60_to_61', 'pop_sex_male_age_under_5', 'households_with_annual_income_30000_to_39999', 'households_with_annual_income_40000_to_49999', 'households_with_annual_income_less_than_30000', 'pop_employment_status_in_labor_force_civilian_unemployed', 'pop_employment_status_not_in_labor_force', 'pop_received_ssi_foodstamps_snap_past_year', 'pop_works_industry_information', 'pop_works_industry_other_services', 'pop_works_industry_transportation_warehousing_utilities', 'pop_works_industry_wholesale_trade', 'pop_works_occupation_production_transportation_moving', 'pop_works_occupation_sales_office', 'pop_works_occupation_service', 'households_cohabiting_couple_with_children', 'households_female_head', 'households_female_head_with_children', 'households_with_computing_devices_none', 'households_with_no_internet_access', 'pop_adult_education_high_school', 'pop_adult_education_less_than_high_school', 'pop_lived_in_same_house_last_year', 'pop_total']

### Mutual Info

In [80]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd

# Calculate mutual information scores
mutual_info = mutual_info_classif(X, y)

# Convert scores to a pandas Series and associate with column names
mutual_info = pd.Series(mutual_info)
mutual_info.index = X.columns

# Sort by mutual information in descending order
sorted_mi = mutual_info.sort_values(ascending=False)

# Plot the scores
sorted_mi.plot.bar(figsize=(20, 8))

# Select top 50 features
top_50_features = sorted_mi.head(50).index

print(top_50_features)

KeyboardInterrupt:

### Model Fitting Again

In [96]:
import statsmodels.api as sm

In [97]:
X = df_main.drop(columns=['fips','2021/3/10_x', '2022/3/10_x', '2023/3/10_x', '2021/3/10_y', '2022/3/10_y', '2023/3/10_y'])
y = df_main['2021/3/10_y']

In [117]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [118]:
X = sm.add_constant(X)
Y = y

In [119]:
model = sm.OLS(Y, X).fit()

In [121]:
p_values = model.pvalues

# Identify variables with p-value > 0.1
vars_to_drop = p_values[p_values > 0.1].index.tolist()
print(vars_to_drop)

# # If you've added a constant to your model, make sure not to drop it
# if 'const' in vars_to_drop:
#     vars_to_drop.remove('const')

# # Drop those variables from X
# X_reduced = X.drop(vars_to_drop, axis=1)

['x1', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x20', 'x21', 'x22', 'x25', 'x26', 'x28', 'x29', 'x36', 'x37', 'x38', 'x39', 'x40', 'x41', 'x44', 'x48', 'x49', 'x50', 'x51', 'x53', 'x54', 'x56', 'x58', 'x60', 'x61', 'x62', 'x63', 'x64', 'x66', 'x69', 'x75', 'x76', 'x77', 'x82', 'x83', 'x84', 'x91', 'x94', 'x96', 'x98', 'x100', 'x101', 'x102', 'x103', 'x104', 'x106', 'x107', 'x109', 'x110', 'x111', 'x112', 'x113', 'x115', 'x117', 'x118', 'x119', 'x120', 'x124', 'x126', 'x127', 'x128', 'x129', 'x130', 'x134', 'x136', 'x138', 'x140', 'x146', 'x147', 'x149', 'x150', 'x152', 'x154', 'x155', 'x158', 'x160', 'x167', 'x171', 'x172', 'x178', 'x183']

In [104]:
X_reduced

,const,Staffed_Beds,Total_Discharges,Patient_Days,Gross_Patient_Revenue,pop_commute_departure_0000_to_0459,pop_commute_departure_0500_to_0529,pop_commute_departure_0530_to_0559,pop_commute_departure_0600_to_0629,pop_commute_departure_0630_to_0659,...,households_with_computing_devices_other_computer,households_with_computing_devices_smartphone,households_with_computing_devices_tablet,households_with_no_internet_access,pop_adult_education_high_school,pop_adult_education_less_than_high_school,pop_lived_in_same_house_last_year,pop_veterans,pop_veterans_female,pop_veterans_male
0,1.0,77.0,3049.0,15984.0,250284.0,1431,1445,881,2362,3063,...,226,17464,12958,3307,8819,2886,48039.0,4559,542,4017
1,1.0,301.0,18080.0,78361.0,2481966.0,3544,3279,4428,10154,11382,...,1467,71134,53324,10018,29636,10250,191350.0,19174,1573,17601
2,1.0,47.0,1055.0,4571.0,76099.0,707,527,539,1204,863,...,200,6404,4231,2700,4525,3131,20996.0,1340,107,1233
3,1.0,156.0,229.0,1053.0,31288.0,426,774,782,1234,867,...,17,5344,3484,1520,5442,2189,19347.0,1205,63,1142
4,1.0,0.0,0.0,0.0,0.0,1634,1566,1597,4375,2858,...,459,16209,10734,3920,9757,4494,52428.0,3408,218,3190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,1.0,58.0,1279.0,4742.0,207720.0,1458,1205,1730,2414,2241,...,515,13713,10585,1498,7298,1656,34743.0,2903,223,2680
3120,1.0,121.0,1711.0,5932.0,273723.0,184,248,398,672,1345,...,438,9084,7185,540,2278,871,18448.0,827,98,729
3121,1.0,32.0,803.0,1627.0,105109.0,684,504,858,537,1097,...,232,6581,5184,531,3960,664,17520.0,952,74,878
3122,1.0,0.0,0.0,0.0,0.0,158,167,147,140,302,...,81,2771,2032,429,1021,308,6667.0,588,23,565
3123,1.0,0.0,0.0,0.0,0.0,419,288,137,254,187,...,47,2233,1464,367,1312,199,5472.0,558,40,518

In [100]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            2021/3/10_y   R-squared:                       0.992
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                     2173.
Date:                Wed, 09 Aug 2023   Prob (F-statistic):               0.00
Time:                        15:38:19   Log-Likelihood:                -17274.
No. Observations:                3124   AIC:                         3.488e+04
Df Residuals:                    2959   BIC:                         3.588e+04
Df Model:                         164
Covariance Type:            nonrobust
==================================================================================================================================
                                                                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------------------
const                                                             -5.6982     25.337     -0.225      0.822     -55.377      43.981
Staffed_Beds                                                      -0.0389      0.022     -1.783      0.075      -0.082       0.004
Total_Discharges                                                  -0.0009      0.000     -1.797      0.072      -0.002    8.08e-05
Patient_Days                                                       0.0003      0.000      2.652      0.008    9.01e-05       0.001
Gross_Patient_Revenue                                          -2.808e-06   1.53e-06     -1.840      0.066    -5.8e-06    1.84e-07
Hospitals                                                         -1.2096      1.990     -0.608      0.543      -5.111       2.692
Local_Hospital                                                    -0.4426      3.518     -0.126      0.900      -7.341       6.455
ADI_NATRANK                                                        0.1519      0.117      1.294      0.196      -0.078       0.382
ADI_STATERNK                                                       0.3832      0.968      0.396      0.692      -1.516       2.282
Value_education                                                    0.0870      1.019      0.085      0.932      -1.910       2.084
Value_poverty                                                      0.2135      0.342      0.624      0.533      -0.458       0.885
Value_unemployment                                                 0.2048      0.229      0.894      0.371      -0.244       0.654
pop_commute_departure_0000_to_0459                                 0.0121      0.002      5.310      0.000       0.008       0.017
pop_commute_departure_0500_to_0529                                 0.0231      0.003      6.673      0.000       0.016       0.030
pop_commute_departure_0530_to_0559                                 0.0091      0.003      2.691      0.007       0.002       0.016
pop_commute_departure_0600_to_0629                                -0.0100      0.003     -3.824      0.000      -0.015      -0.005
pop_commute_departure_0630_to_0659                                 0.0043      0.002      1.793      0.073      -0.000       0.009
pop_commute_departure_0700_to_0729                                 0.0060      0.002      3.327      0.001       0.002       0.010
pop_commute_departure_0730_to_0759                                -0.0094      0.002     -5.128      0.000      -0.013      -0.006
pop_commute_departure_0800_to_0829                                -0.0003      0.002     -0.136      0.892      -0.004       0.004
pop_commute_departure_0830_to_0859                                -0.0030      0.003     -1.012      0.312      -0.009       0.003
pop_commute_departure_0900_to_0959                                -0.0039      0.003     -1.207      0.227      -0.010       0.002
pop_commute_departure_1000_to_1059                                 0.0116      0.005      2.119      0.034       0.001       0.022
pop_commute_departure_1100_to_1159                                -0.0169      0.008     -2.094      0.036      -0.033      -0.001
pop_commute_departure_1200_to_1559                                -0.0041      0.003     -1.391      0.164      -0.010       0.002
pop_commute_departure_1600_to_2359                                -0.0043      0.003     -1.578      0.115      -0.010       0.001
pop_commute_travel_time_10_to_14_min                               0.0053      0.002      2.570      0.010       0.001       0.009
pop_commute_travel_time_15_to_19_min                              -0.0006      0.002     -0.333      0.739      -0.004       0.003
pop_commute_travel_time_20_to_24_min                              -0.0009      0.002     -0.524      0.600      -0.004       0.003
pop_commute_travel_time_25_to_29_min                               0.0045      0.002      2.122      0.034       0.000       0.009
pop_commute_travel_time_30_to_34_min                               0.0035      0.002      1.929      0.054   -5.76e-05       0.007
pop_commute_travel_time_35_to_39_min                              -0.0102      0.005     -2.122      0.034      -0.020      -0.001
pop_commute_travel_time_40_to_44_min                               0.0080      0.004      1.793      0.073      -0.001       0.017
pop_commute_travel_time_45_to_59_min                              -0.0061      0.003     -2.409      0.016      -0.011      -0.001
pop_commute_travel_time_5_to_9_min                                 0.0058      0.002      2.567      0.010       0.001       0.010
pop_commute_travel_time_60_to_89_min                              -0.0014      0.002     -0.652      0.515      -0.005       0.003
pop_commute_travel_time_90_min_or_more                             0.0033      0.003      1.293      0.196      -0.002       0.008
pop_commute_travel_time_under_5_min                                0.0031      0.004      0.879      0.379      -0.004       0.010
pop_commutes_by_bicycle                                            0.0111      0.007      1.532      0.126      -0.003       0.025
pop_commutes_by_car_truck_van_alone                               -0.0020      0.001     -2.296      0.022      -0.004      -0.000
pop_commutes_by_car_truck_van_any                                  0.0008      0.001      0.591      0.555      -0.002       0.003
pop_commutes_by_car_truck_van_carpool                              0.0028      0.001      2.263      0.024       0.000       0.005
pop_commutes_by_public_transport_any                               0.0462      0.015      3.120      0.002       0.017       0.075
pop_commutes_by_public_transport_bus                               0.0067      0.020      0.340      0.734      -0.032       0.045
pop_commutes_by_public_transport_ferry                            -0.0065      0.002     -3.211      0.001      -0.011      -0.003
pop_commutes_by_public_transport_lightrail                         0.0029      0.002      1.585      0.113      -0.001       0.007
pop_commutes_by_public_transport_rail                             -0.0064      0.002     -2.765      0.006      -0.011      -0.002
pop_commutes_by_public_transport_subway                           -0.0006      0.002     -0.223      0.823      -0.005       0.004
pop_commutes_by_taxi_motorcycle_or_other                          -0.0082      0.012     -0.715      0.475      -0.031       0.014
pop_commutes_by_walking                                           -0.0016      0.005     -0.295      0.768      -0.012       0.009
pop_has_0_vehicles_available                                      -0.0004      0.004     -0.099      0.922      -0.008       0.007
pop_has_1_vehicles_available                                       0.0109      0.004      2.882      0.004       0.003       0.018
pop_has_2_vehicles_available                                      -0.0030      0.004     -0.804      0.421      -0.010       0.004
pop_has_3_or_more_vehicles_available                              -0.0050      0.004     -1.377      0.169      -0.012       0.002
pop_works_from_home                                               -0.0632      0.020     -3.138      0.002      -0.103      -0.024
pop_works_in_county_of_residence                                   0.0008      0.002      0.442      0.658      -0.003       0.004
pop_works_in_state_different_county_of_residence                   0.0026      0.002      1.401      0.161      -0.001       0.006
pop_works_in_state_of_residence                                    0.0034      0.004      0.922      0.357      -0.004       0.011
pop_works_outside_state_of_residence                               0.0067      0.006      1.216      0.224      -0.004       0.018
median_age                                                        -0.3058      2.395     -0.128      0.898      -5.002       4.391
median_age_female                                                 -0.3617      1.245     -0.291      0.771      -2.803       2.080
median_age_male                                                    0.3229      1.389      0.232      0.816      -2.401       3.047
pop_birthplace_foreign                                             0.0004      0.001      0.277      0.782      -0.002       0.003
pop_birthplace_us                                                  0.0002      0.001      0.200      0.841      -0.002       0.002
pop_citizenship_non_us                                            -0.0020      0.001     -2.504      0.012      -0.004      -0.000
pop_citizenship_us_native                                          0.0002      0.001      0.200      0.841      -0.002       0.002
pop_citizenship_us_naturalized                                     0.0024      0.001      2.854      0.004       0.001       0.004
pop_ethnicity_hispanic_latino                                      0.0010      0.001      0.880      0.379      -0.001       0.003
pop_ethnicity_non_hispanic                                        -0.0004      0.001     -0.399      0.690      -0.003       0.002
pop_race_asian                                                    -0.0012      0.000     -2.376      0.018      -0.002      -0.000
pop_race_black                                                    -0.0011      0.000     -2.899      0.004      -0.002      -0.000
pop_race_hawaiian_pacific_islander                                 0.0060      0.002      3.137      0.002       0.002       0.010
pop_race_multiple                                                 -0.0082      0.001     -8.150      0.000      -0.010      -0.006
pop_race_native_american                                           0.0042      0.001      7.568      0.000       0.003       0.005
pop_race_other                                                 -1.113e-05      0.000     -0.023      0.982      -0.001       0.001
pop_race_white                                                     0.0008      0.000      1.986      0.047       1e-05       0.002
pop_sex_female                                                     0.0058      0.002      3.018      0.003       0.002       0.010
pop_sex_female_age_10_to_14                                        0.0128      0.011      1.144      0.253      -0.009       0.035
pop_sex_female_age_15_to_17                                       -0.0694      0.014     -4.821      0.000      -0.098      -0.041
pop_sex_female_age_18_to_19                                       -0.0477      0.007     -6.578      0.000      -0.062      -0.033
pop_sex_female_age_20                                              0.0447      0.009      5.092      0.000       0.027       0.062
pop_sex_female_age_21                                              0.0088      0.008      1.107      0.268      -0.007       0.024
pop_sex_female_age_22_to_24                                        0.0055      0.006      0.880      0.379      -0.007       0.018
pop_sex_female_age_25_to_29                                        0.0030      0.009      0.335      0.738      -0.014       0.020
pop_sex_female_age_30_to_34                                       -0.0548      0.010     -5.245      0.000      -0.075      -0.034
pop_sex_female_age_35_to_39                                       -0.0348      0.008     -4.637      0.000      -0.050      -0.020
pop_sex_female_age_40_to_44                                       -0.0337      0.008     -4.176      0.000      -0.050      -0.018
pop_sex_female_age_45_to_49                                        0.0447      0.012      3.616      0.000       0.020       0.069
pop_sex_female_age_50_to_54                                        0.0183      0.013      1.395      0.163      -0.007       0.044
pop_sex_female_age_55_to_59                                        0.0279      0.008      3.528      0.000       0.012       0.043
pop_sex_female_age_5_to_9                                         -0.0094      0.011     -0.824      0.410      -0.032       0.013
pop_sex_female_age_60_to_61                                        0.0150      0.010      1.557      0.120      -0.004       0.034
pop_sex_female_age_62_to_64                                        0.0629      0.009      6.993      0.000       0.045       0.081
pop_sex_female_age_65_to_66                                       -0.0154      0.010     -1.475      0.140      -0.036       0.005
pop_sex_female_age_67_to_69                                       -0.0425      0.009     -4.531      0.000      -0.061      -0.024
pop_sex_female_age_70_to_74                                       -0.0059      0.008     -0.709      0.479      -0.022       0.011
pop_sex_female_age_75_to_79                                        0.0343      0.009      3.817      0.000       0.017       0.052
pop_sex_female_age_80_to_84                                       -0.0044      0.009     -0.496      0.620      -0.022       0.013
pop_sex_female_age_85_and_over                                     0.0455      0.007      6.631      0.000       0.032       0.059
pop_sex_female_age_under_5                                         0.0005      0.013      0.040      0.968      -0.025       0.026
pop_sex_male                                                      -0.0052      0.002     -2.851      0.004      -0.009      -0.002
pop_sex_male_age_10_to_14                                          0.0151      0.011      1.369      0.171      -0.007       0.037
pop_sex_male_age_15_to_17                                          0.0130      0.014      0.950      0.342      -0.014       0.040
pop_sex_male_age_18_to_19                                          0.0056      0.008      0.672      0.502      -0.011       0.022
pop_sex_male_age_20                                               -0.0146      0.008     -1.786      0.074      -0.031       0.001
pop_sex_male_age_21                                                0.0043      0.008      0.531      0.595      -0.011       0.020
pop_sex_male_age_22_to_24                                          0.0007      0.006      0.128      0.898      -0.011       0.012
pop_sex_male_age_25_to_29                                          0.0347      0.008      4.408      0.000       0.019       0.050
pop_sex_male_age_30_to_34                                          0.0115      0.010      1.149      0.250      -0.008       0.031
pop_sex_male_age_35_to_39                                         -0.0069      0.007     -0.989      0.323      -0.021       0.007
pop_sex_male_age_40_to_44                                         -0.0028      0.007     -0.375      0.708      -0.017       0.012
pop_sex_male_age_45_to_49                                         -0.0026      0.011     -0.233      0.815      -0.025       0.019
pop_sex_male_age_50_to_54                                          0.0022      0.013      0.170      0.865      -0.023       0.028
pop_sex_male_age_55_to_59                                         -0.0402      0.008     -4.928      0.000      -0.056      -0.024
pop_sex_male_age_5_to_9                                            0.0202      0.012      1.753      0.080      -0.002       0.043
pop_sex_male_age_60_to_61                                         -0.0257      0.009     -2.777      0.006      -0.044      -0.008
pop_sex_male_age_62_to_64                                         -0.0126      0.009     -1.367      0.172      -0.031       0.005
pop_sex_male_age_65_to_66                                          0.0036      0.011      0.332      0.740      -0.018       0.025
pop_sex_male_age_67_to_69                                          0.0061      0.010      0.591      0.555      -0.014       0.026
pop_sex_male_age_70_to_74                                          0.0177      0.010      1.771      0.077      -0.002       0.037
pop_sex_male_age_75_to_79                                         -0.0284      0.009     -3.098      0.002      -0.046      -0.010
pop_sex_male_age_80_to_84                                          0.0331      0.011      3.108      0.002       0.012       0.054
pop_sex_male_age_85_and_over                                      -0.0390      0.010     -3.733      0.000      -0.059      -0.019
pop_sex_male_age_under_5                                          -0.0003      0.012     -0.028      0.978      -0.023       0.023
households_total_x                                                -0.0042      0.001     -4.338      0.000      -0.006      -0.002
households_with_annual_income_100000_to_124999                    -0.0024      0.004     -0.624      0.533      -0.010       0.005
households_with_annual_income_125000_to_149999                     0.0051      0.004      1.170      0.242      -0.003       0.014
households_with_annual_income_150000_to_199999                     0.0061      0.004      1.717      0.086      -0.001       0.013
households_with_annual_income_200000_or_more                      -0.0029      0.002     -1.847      0.065      -0.006       0.000
households_with_annual_income_30000_to_39999                       0.0055      0.004      1.500      0.134      -0.002       0.013
households_with_annual_income_40000_to_49999                      -0.0086      0.004     -2.277      0.023      -0.016      -0.001
households_with_annual_income_50000_to_59999                       0.0237      0.004      5.576      0.000       0.015       0.032
households_with_annual_income_60000_to_75499                      -0.0148      0.004     -3.931      0.000      -0.022      -0.007
households_with_annual_income_75000_to_99999                      -0.0042      0.003     -1.307      0.191      -0.011       0.002
households_with_annual_income_less_than_30000                     -0.0117      0.002     -7.170      0.000      -0.015      -0.009
pop_employment_status_in_labor_force                              -0.0316      0.020     -1.620      0.105      -0.070       0.007
pop_employment_status_in_labor_force_armed_forces                 -0.1107      0.055     -2.002      0.045      -0.219      -0.002
pop_employment_status_in_labor_force_civilian_employed             0.0317      0.019      1.696      0.090      -0.005       0.068
pop_employment_status_in_labor_force_civilian_unemployed           0.0474      0.019      2.554      0.011       0.011       0.084
pop_employment_status_not_in_labor_force                          -0.0002      0.009     -0.029      0.977      -0.017       0.017
pop_received_ssi_foodstamps_snap_past_year                        -0.0048      0.001     -4.101      0.000      -0.007      -0.002
pop_works_industry_agriculture_forestry_fishing_hunting_mining    -0.0295      0.005     -5.793      0.000      -0.039      -0.020
pop_works_industry_armed_forces                                    0.1246      0.068      1.839      0.066      -0.008       0.258